theme: minima
title: Sura Karthikeya
author: @abhinit21
email: surak504@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey! Good to see you on this page. I made this page to learn GitHub and GitHub Pages.
  Check my profile for all the projects I have posted. Short decription :
  Computer Science Engineer | Technophile

# social links
twitter_username: _Karthikeya # DO NOT include the @ character, or else the build will fail!
github_username:  abhinit21 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
